
teracy-dev-certs:
  # the node id which certs will provision
  node_id: "0" # 0 by default from teracy-dev-core
  ansible:
    mode: guest # or host to run ansible from the host machine
    install_mode: pip
    version: # ansible guest version
  ca_days: 2000 # valid days for the root CA cert
  cert:
    days: 2000
    generated: true # enabled by default to generate a CA signed certificate
  common_name: "%{node_hostname_prefix}.%{node_domain_affix}"
  alt_names:
    - "%{node_hostname_prefix}.%{node_domain_affix}"

  # don't try to change node_template if you don't know what you're going to do
  # node template to be overriden
  node_template:
    _id: "0"
    provisioners:
      - _id: certs-ansible
        type: ansible_local
        name: teracy-dev-certs
        verbose: -vv
        weight: 8
        enabled: true
        playbook: "%{teracy-dev-certs-path}/provisioners/ansible/certs.yaml"
